## Skewness
A negative skew means that you get more negative returns than you would have expected if the returns were distributed like the normal distribution.

If returns are negatively skewed, the expected value i.e. the mean is less than the median. If they are positively skewed, the expected value (again, the mean) is greater than the median.


$$ S(R) = \frac{E[ (R-E(R))^3 ]}{\sigma_R^3} $$



## Kurtosis


Kurtosis measures the "fatness" of the tails of the distribution. The normal distribution has a kurtosis of 3 and so if the kurtosis of your returns is less than 3 then it tends to have thinner tails, and if the kurtosis is greater than 3 then the distribution has fatter tails.

$$ K(R) = \frac{E[ (R-E(R))^4 ]}{\sigma_R^4} $$



## Jarque-Bera Test

Jarque-Bera is used to check how normal a distribution is

In [13]:
%load_ext autoreload
%autoreload 2
%config Completer.use_jedi = False

import pandas as pd
import risk_kit as erk

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
hfi = erk.get_hfi_returns()
hfi

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   
...                        ...         ...                    ...   
2018-07                 0.0021     -0.0058                 0.0093   
2018-08                 0.0024      0.0166                 0.0002   
2018-09                 0.0034     -0.0054                 0.0050   
2018-10                -0.0073     -0.0314                -0.0158   
2018-11                -0.0068     -0.0053                -0.0193   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   
...                   ...                    ...           ...   
2018-07            0.0040                -0.0010        0.0055   
2018-08           -0.0277                 0.0004        0.0011   
2018-09           -0.0110                -0.0016        0.0032   
2018-10           -0.0315                -0.0129       -0.0257   
2018-11            0.0120                -0.0211       -0.0034   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   
...                         ...           ...                ...   
2018-07                  0.0022       -0.0014             0.0067   
2018-08                  0.0017       -0.0007             0.0035   
2018-09                  0.0036        0.0006            -0.0023   
2018-10                 -0.0023       -0.0096            -0.0402   
2018-11                 -0.0067       -0.0087            -0.0044   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275  
...                   ...             ...            ...             ...  
2018-07           -0.0021          0.0045        -0.0052          0.0018  
2018-08            0.0050         -0.0002        -0.0214          0.0015  
2018-09            0.0028          0.0018         0.0036         -0.0022  
2018-10           -0.0080         -0.0109         0.0237         -0.0269  
2018-11            0.0119         -0.0063        -0.0021         -0.0071  

[263 rows x 13 columns]

In [15]:
pd.concat([hfi.mean(), hfi.median(), hfi.mean()>hfi.median()], axis="columns")

0       1      2
Convertible Arbitrage   0.005508  0.0065  False
CTA Global              0.004074  0.0014   True
Distressed Securities   0.006946  0.0089  False
Emerging Markets        0.006253  0.0096  False
Equity Market Neutral   0.004498  0.0051  False
Event Driven            0.006344  0.0084  False
Fixed Income Arbitrage  0.004365  0.0055  False
Global Macro            0.005403  0.0038   True
Long/Short Equity       0.006331  0.0079  False
Merger Arbitrage        0.005356  0.0060  False
Relative Value          0.005792  0.0067  False
Short Selling          -0.001701 -0.0053   True
Funds Of Funds          0.004262  0.0052  False

### Skewness

$$ S(R) = \frac{E[ (R-E(R))^3 ]}{\sigma_R^3} $$


In [11]:
def skewness(rets):
    demeaned_rets = rets - rets.mean()
    exp = (demeaned_rets ** 3).mean()
    sigma_r = rets.std(ddof=0)     # population sdt (ddof=0)
    return exp / sigma_r ** 3

In [21]:
sk = skewness(hfi)
sk

Convertible Arbitrage    -2.639592
CTA Global                0.173699
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Equity Market Neutral    -2.124435
Event Driven             -1.409154
Fixed Income Arbitrage   -3.940320
Global Macro              0.982922
Long/Short Equity        -0.390227
Merger Arbitrage         -1.320083
Relative Value           -1.815470
Short Selling             0.767975
Funds Of Funds           -0.361783
dtype: float64

#### Python built in skewness

In [20]:
import scipy.stats

scipy.stats.skew(hfi)

array([-2.63959223,  0.17369864, -1.30084204, -1.16706749, -2.12443538,
       -1.40915356, -3.94032029,  0.98292188, -0.39022677, -1.32008333,
       -1.81546975,  0.76797484, -0.36178308])

In [23]:
# testing and comparing skewness with random rets

import numpy as np

normal_rets = np.random.normal(0, .15, size=(263, 1))

sk = skewness(normal_rets)
sk

0.10423719998823726

In [24]:
sk_builtin = scipy.stats.skew(normal_rets)
sk_builtin

array([0.1042372])

### Kurtosis
$$ K(R) = \frac{E[ (R-E(R))^4 ]}{\sigma_R^4} $$


In [26]:
def kurtosis(rets):
    demeaned_rets = rets - rets.mean()
    exp = (demeaned_rets ** 4).mean()
    sigma_r = rets.std(ddof=0)     # population sdt (ddof=0)
    return exp / sigma_r ** 4

In [27]:
kurtosis(normal_rets)

2.8010826257697325

In [28]:
kurtosis(hfi) 

Convertible Arbitrage     23.280834
CTA Global                 2.952960
Distressed Securities      7.889983
Emerging Markets           9.250788
Equity Market Neutral     17.218555
Event Driven               8.035828
Fixed Income Arbitrage    29.842199
Global Macro               5.741679
Long/Short Equity          4.523893
Merger Arbitrage           8.738950
Relative Value            12.121208
Short Selling              6.117772
Funds Of Funds             7.070153
dtype: float64

#### Python built in kurtosis

In [30]:
scipy.stats.kurtosis(normal_rets)   # !!!! Excess kurtosis --> kurtosis - 3

array([-0.19891737])

In [32]:
kurtosis(normal_rets) - 3

-0.19891737423026745

### Jarque-Bera Test


In [34]:
scipy.stats.jarque_bera(normal_rets)
# pvalue is the confidence that the distribution is normal

Jarque_beraResult(statistic=0.9098670986610248, pvalue=0.6344901288412477)

In [37]:
def is_normal(rets, level=0.01):
    # 1% level of confidence as default
    statistic, pvalue = scipy.stats.jarque_bera(rets)
    return pvalue > level
    

In [38]:
is_normal(normal_rets)

True

In [40]:
is_normal(hfi)

False

In [41]:
hfi.aggregate(is_normal) ## !!! APPLY is_normal on each column

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities     False
Emerging Markets          False
Equity Market Neutral     False
Event Driven              False
Fixed Income Arbitrage    False
Global Macro              False
Long/Short Equity         False
Merger Arbitrage          False
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool